# Generated by Django 4.0.2 on 2024-05-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUsers', '0002_customtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSystemRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_token', models.CharField(max_length=255)),
                ('user_id_connected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customUsers.customuser')),
            ],
            options={
                'db_table': 'remote_systems',
            },
        ),
    ]
