# Generated by Django 4.0.2 on 2024-05-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUsers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customUsers.customuser')),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='FarmConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(max_length=15)),
                ('condition_rule', models.CharField(max_length=12)),
                ('notify_at', models.FloatField(max_length=255)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farm')),
            ],
            options={
                'db_table': 'conditions',
            },
        ),
    ]
