# Generated by Django 4.2.11 on 2024-05-09 18:02

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=1000000, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\youss\\Documents\\Youssof\\LIU\\CENG495 - Senior Project\\backend\\farminator\\farm/static'), upload_to='farms/')),
                ('product_id', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customUsers.customuser')),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='FarmConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(max_length=15)),
                ('condition_rule', models.CharField(max_length=12)),
                ('notify_at', models.FloatField(max_length=255)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farm')),
            ],
            options={
                'db_table': 'conditions',
            },
        ),
    ]
