# Generated by Django 4.0.2 on 2024-05-09 20:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(max_length=1000000, storage=django.core.files.storage.FileSystemStorage(location=None), upload_to='farms/'),
        ),
    ]
