# Generated by Django 4.2.11 on 2024-05-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_farm_image'),
        ('farm', '0002_farmconditions'),
    ]

    operations = [
    ]
