# Generated by Django 5.0.6 on 2024-05-20 15:53

import django.core.files.storage
import farm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_farm_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='farmconditions',
            old_name='farm_id',
            new_name='farm',
        ),
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(max_length=1000000, storage=django.core.files.storage.FileSystemStorage(location=None), upload_to=farm.models.get_image_upload_path),
        ),
    ]
